### ISSUE TITLE
Bar Charts: Dash

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_king_pilot_dashboard#2]

**Comment by ReedRodgers** [comment]
- [ ] Generate fast basic data
- [ ] Build a bare-bones barchart

**Comment by ReedRodgers** [comment]
- [ ] add labels and formatting to bare-bones barchart
- [ ] add another graph to the dashboard

**Comment by ReedRodgers** [comment]
- [x] Fix annotation text
