### ISSUE TITLE
street_volumes.json data not loading/displaying

### ISSUE THREAD

**Issue by rcyyu** [CityofToronto/bdit_king_pilot_dashboard#21]
Data has been converted from the database table `ryu4.street_tiled_kingstreetpilot` to street_volumes.json. However, loading the data onto the webmap using the code:
```
sources:
    mapzen:
        type: GeoJSON
        url: street_volumes.json
```
fails to display the data. No error messages are generated in the browser such as `Tangram v0.10.6 [warn]: data source load error(s) for source 'mapzen', URL 'http://localhost:8000/street_volumes.geojson': [357]</i.io/o</i.onload@https://mapzen.com/tangram/0.10/tangram.min.js:19:17191` which would generate if the file was not found.
This problem may have been caused by:
- Incorrect JSON format
- The `scene.yaml` file loads the data, but doesn't utilize/display it correctly
- Something else that I haven't thought about

The [github page](https://github.com/CityofToronto/bdit_king_pilot_dashboard/blob/gh-pages/data/street_volumes.json) fails to display the data, so the data format is likely to be incorrect.

**Comment by radumas** [comment]
Should be fixed by https://github.com/CityofToronto/bdit_king_pilot_dashboard/commit/89b728c6bd84a4860aea3537ef00b7a196c7cea0

**Comment by rcyyu** [comment]
Confirmed fixed. CRS needed to be provided in JSON string in addition project was EPSG:4326 not EPSG:3857.
