### ISSUE TITLE
Graph Alignment & Layout

### ISSUE THREAD

**Issue by ReedRodgers** [CityofToronto/bdit_king_pilot_dashboard#35]
Aligning graphs horizontally seems tricky, making a plotly subplot doesn't play well with interactivity, as the callback function returns a figure to core.Graph, where subplots takes traces, used to produce figures.

Applying html styling doesn't seem to make it down to the appropriate div container in dcc.Graph, having tried applying inline style to the graph's container, and dcc.Graph itself.

**Comment by radumas** [comment]
Have you looked at this? Since you have 6 graphs you could assign each of them 2-columns.
https://community.plot.ly/t/orient-2-graphs-based-on-window-aspect-mobile-responsiveness/5475

**Comment by ReedRodgers** [comment]
Thanks Raph, I just implemented your solution.
