### ISSUE TITLE
Volumes Map: Leaflet

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_king_pilot_dashboard#5]

**Comment by rcyyu** [comment]
- [x] Create table containing geometry of King Street Pilot streets
- [x] Create webpage to demo Leaflet map containing King Street Pilot streets
- [x] Convert table `ryu4.streets_tiled_kingstreetpilot` to JSON
- [x] Connect JSON to web page using `scene.yaml` with relative path to JSON.
- [x] Stylize map
- - [x] Remove/Add needed roads
- - [ ] Group road segments
- - [x] Create legend
- [x] Combine year/month/day data into one JSON file
- [x] Optimize labeling on map
- [ ] Create Average Pct Change on King Label
