### ISSUE TITLE
Dashboard - Design Layout

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_king_pilot_dashboard#53]

**Comment by radumas** [comment]
- [x] Change title to **King Street Transit Pilot: Daily Travel Time Monitoring**
- [x] Colour day type and timeperiod buttons differently
- [x] Remove white space around plots
- [x] Add from-to street above plot

**Comment by radumas** [comment]
Final subtask requires #70 to happen first

**Comment by radumas** [comment]
- [x] Change plot aspect ratio

**Comment by radumas** [comment]
- [x] Label baseline line
 - [ ] Label every x-axis day
 - [x] Add BDIT Team name

**Comment by radumas** [comment]
- [x] Fix x-axis to date-range

**Comment by radumas** [comment]
@jwrcoleman @aharpalaniTO I think I'm going to have to put a box around the baseline text 
![baseline](https://user-images.githubusercontent.com/10623872/32919792-01b1e338-caf5-11e7-9984-e4eeb6e8a781.PNG)

**Comment by radumas** [comment]
Alternatively, commit above moves the axis over a little and shift the text to the left
![baseline_new1](https://user-images.githubusercontent.com/10623872/32920274-a4eff764-caf6-11e7-961f-61a7439f01d5.PNG)![baseline_new2](https://user-images.githubusercontent.com/10623872/32920277-a7ca518c-caf6-11e7-8e23-c2852d9c7f57.PNG)
