### ISSUE TITLE
Data Input

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_king_pilot_dashboard#6]

**Comment by radumas** [comment]
- [x] Create street_volumes geojson (https://github.com/CityofToronto/bdit_king_pilot_dashboard/commit/1170767730008f8cf1d9a8d945362e6ec9c4338a)
 - [ ] Create car travel time 
 - [ ] Create streetcar headway reliability 
 - [ ] Create average streetcar travel time

## Car Travel Time  
|id | corridor | direction | time period | month | travel time |
|--|-----------|-----------|--------------|---------|-------------|
| 1,2| [Dundas, Queen, Front, Adelaide, Richmond, Wellington] | [EB, WB] | [AM, PM] | 2017-10-10, etc. | 10-15|

## Streetcar Headway Reliability 
| month | direction | time period | pct_reliable_headways|
|---------|-----------|--------------|-------------------------|
| 2017-10-10, etc. | [EB, WB] | [AM, PM] | 60%-95%|

## Streetcar Travel Time
|id | section| month | direction | time period | travel_time|
|--|-----------|---------|-----------|--------------|-------------------------|
| 1,2 | [Bathurst-Spadina, Spadina-University, University-Yonge, Yonge-Jarvis] | 2017-10-10, etc. | [EB, WB] | [AM, PM] | 60%-95%|

**Comment by aharpalaniTO** [comment]
@radumas - for the fake data file: can you create fake data for 3+ months? I'm assuming October 2017 is indicative of baseline. Would like to test transitions for different months. Thanks!
