### ISSUE TITLE
Dashboard - Update Data View

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_king_pilot_dashboard#70]
- [x] Include timeperiod ranges 
If timeperiod ranges are a separate column, should solve problem of ordering the time periods

**Comment by aharpalaniTO** [comment]
Currently a column in `king_pilot.periods`. Will add to the views `king_pilot.dash_daily`

**Comment by radumas** [comment]
- [x] Add from-to streets to baseline
