### ISSUE TITLE
Dashboard - Bug - Nov 12 not showing up on plots

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_king_pilot_dashboard#75]
Data for Nov 12 shows up in table, but no related data point appears on either plot.

**Comment by radumas** [comment]
Dash seems to have difficulty with a bar graph with only one value. If I remove the splitting of data into baseline & after, Nov 12th displays fine.
![image](https://user-images.githubusercontent.com/10623872/32965930-33870df0-cba6-11e7-8181-d96b989ea219.png)
