### ISSUE TITLE
Dashboard - Add NS Streets

### ISSUE THREAD

**Issue by radumas** [CityofToronto/bdit_king_pilot_dashboard#82]

**Comment by aharpalaniTO** [comment]
- [x] Add relevant N/S streets to `king_pilot.dash_daily` and `king_pilot.dash_baseline`
- [ ] Modify segment ordering list within Dash script

Also: add tab for N/S streets (see #88)

**Comment by radumas** [comment]
Tabs added by https://github.com/CityofToronto/bdit_king_pilot_dashboard/commit/2343abdc41b9ff568adb07aa6ca7b37c1e5a7437

Will need to update `STREETS` global var mentioned above.
Will need to modify `display_content()` callback function triggered by tabs to display the `STREETS_LAYOUT` when N/S data added. See https://github.com/CityofToronto/bdit_king_pilot_dashboard/blob/2343abdc41b9ff568adb07aa6ca7b37c1e5a7437/app.py#L373

**Comment by radumas** [comment]
Bit of a hurdle with the `row_click()` callback function. The callback doesn't fire if all of the Inputs don't exist. at the time of one of them firing the callback. Need to update this by splitting into two functions, one for each orientation of street.

https://github.com/CityofToronto/bdit_king_pilot_dashboard/blob/2343abdc41b9ff568adb07aa6ca7b37c1e5a7437/app.py#L423-L446
