### ISSUE TITLE
Dashboard - Add tab functionality

### ISSUE THREAD

**Issue by aharpalaniTO** [CityofToronto/bdit_king_pilot_dashboard#88]
Currently three planned tabs:
- Auto E/W
- Auto N/S
- Transit

**Comment by radumas** [comment]
[Explainer](https://github.com/plotly/dash-core-components/pull/74)

**Comment by radumas** [comment]
[Some tab comments](https://community.plot.ly/t/dcc-tabs-filling-tabs-with-dynamic-content-how-to-organize-the-callbacks/6377)
